# Generated by Django 3.0.6 on 2020-05-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], max_length=1)),
                ('kind', models.CharField(choices=[('C', 'Cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('S', 'Special')], max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('price', models.FloatField()),
            ],
        ),
    ]
