# Generated by Django 3.0.6 on 2020-05-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
