# Generated by Django 3.0.6 on 2020-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200520_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('can_have_topping', models.IntegerField()),
                ('exact_number_of_toppings', models.IntegerField()),
                ('small_price', models.FloatField()),
                ('large_price', models.FloatField()),
                ('each_topping_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Food_topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ManyToManyField(blank=True, related_name='food', to='orders.Food')),
                ('topping_id', models.ManyToManyField(blank=True, related_name='topping', to='orders.Topping')),
            ],
        ),
        migrations.DeleteModel(
            name='Dinner_Platter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
