# Generated by Django 3.0.6 on 2020-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200528_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='topping', to='orders.Topping'),
        ),
        migrations.DeleteModel(
            name='Food_topping',
        ),
    ]
