# Generated by Django 3.0.6 on 2020-05-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200530_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='toppings',
        ),
        migrations.CreateModel(
            name='Food_topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ManyToManyField(blank=True, related_name='food', to='orders.Food')),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping')),
            ],
        ),
    ]
